// Encrypted messages for the decoder. Generated by a private tool; contains no plaintext.
export const BLOBS = [
  {
    "iv": "musFJLOV2zaiKBpG",
    "ct": "aKuy8lfxvV1DY0XkImp1v/MpbowKAFl7szAXZ8LbBMubgsMMHzmW/w=="
  },
  {
    "iv": "L98C4u7WIOvRD/h1",
    "ct": "3qPZJMYdBNpJ2vUL7zAzvntFXubpX3KJLpmHPcNDjhmW/KXyh2uKd3zJ6jtefypeCsGp3kAF5sEfd/gol1qaDbR4wO+e6mrFuLJwNK373BrTQDADo3nOuDGVefrsmNk1VOSPwZUzUeakLceYll7rQC8omKu/ru8jorvT/Bu12uyf"
  },
  {
    "iv": "mGZP9a8sU4ldmkWl",
    "ct": "JlW2Ztw2sludKYfgZv9Jp+gBKmyoi6whznRd6K/Doc1V3EcZ+88msA=="
  }
];
